# Generated by Django 2.2.4 on 2019-08-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190828_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsavel', models.CharField(max_length=50, verbose_name='REsponsavel')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('horario_funcionamento', models.DateTimeField(verbose_name='Horario de funcionamento')),
                ('endereco', models.CharField(max_length=10, verbose_name='Endereço')),
                ('str_numero', models.CharField(max_length=5, verbose_name='Número Res.')),
                ('complemento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento')),
                ('telefone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefone')),
                ('obs', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.CharField(max_length=255, unique=True, verbose_name='email'),
        ),
    ]
