# Generated by Django 2.2.4 on 2019-08-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190829_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ong',
            name='endereco',
            field=models.CharField(max_length=10, verbose_name='endereco'),
        ),
        migrations.AlterField(
            model_name='ong',
            name='horario_funcionamento',
            field=models.DateTimeField(verbose_name='horario_funcionamento'),
        ),
        migrations.AlterField(
            model_name='ong',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='ong',
            name='responsavel',
            field=models.CharField(max_length=50, verbose_name='responsavel'),
        ),
    ]
